command: [
  "uvicorn",
  "server.app:app"
]

env:
  - name: CATALOG_NAME
    value: jmr_demo
  - name: SCHEMA_NAME
    value: zerobus_sdp
  - name: DATA_BACKEND
    value: lakebase
  - name: LAKEBASE_INSTANCE_NAME
    value: zerobus-dev
  - name: LAKEBASE_DATABASE_NAME
    value: zerobus_sdp
  - name: LAKEBASE_CATALOG_NAME
    value: zerobus_sdp
  - name: LAKEBASE_SCHEMA_NAME
    value: zerobus_sdp
  - name: LAKEBASE_HOST
    value: instance-fc55fde4-a0a8-4e28-beca-73f5a4833f4e.database.cloud.databricks.com
  - name: LAKEBASE_PORT
    value: "5432"

resources:
  - name: lakebase-instance
    database_instance:
      id: zerobus-dev
      permission: CAN_USE
  - name: warehouse
    sql_warehouse:
      auto_detect: true
      permission: CAN_USE
