command: [
  "uvicorn",
  "server.app:app"
]

env:
  - name: CATALOG_NAME
    value: jmr_demo
  - name: SCHEMA_NAME
    value: zerobus_sdp
  - name: DATA_BACKEND
    value: lakebase
  - name: LAKEBASE_INSTANCE_NAME
    value: zerobus-dev
  - name: LAKEBASE_DATABASE_NAME
    value: zerobus_sdp
  - name: LAKEBASE_CATALOG_NAME
    value: zerobus_sdp
  - name: LAKEBASE_SCHEMA_NAME
    value: zerobus_sdp
  - name: LAKEBASE_HOST
    value: instance-7c3b2c57-f707-4188-acf5-a0101ad63c36.database.cloud.databricks.com
  - name: LAKEBASE_PORT
    value: "5432"
  - name: OTEL_SERVICE_NAME
    value: o11y-app-backend
  - name: ENVIRONMENT
    value: production
  - name: OTEL_CATALOG
    value: jmr_demo
  - name: OTEL_SCHEMA
    value: zerobus
  - name: OTEL_TABLE_PREFIX
    value: otel
  - name: DATABRICKS_OTEL_TOKEN
    valueFrom: {{secrets.otel-token}}
  - name: DATABRICKS_HOST
    value: https://e2-demo-field-eng.cloud.databricks.com

resources:
  - name: otel-token
    secret:
      scope: jmr_demo
      key: otel_token
      permission: READ
  - name: lakebase-instance
    database_instance:
      id: zerobus-dev
      permission: CAN_USE
  - name: warehouse
    sql_warehouse:
      auto_detect: true
      permission: CAN_USE
