resources:
  apps:
    o11y_jmr_app:
      name: o11y-jmr
      description: Observability dashboard for distributed tracing and service metrics (Lakebase backend)
      source_code_path: ${workspace.file_path}
      config:
        command: ["uvicorn","server.app:app"]
        env:
          - name: LAKEBASE_INSTANCE_NAME
            value: zerobus-dev
          - name: LAKEBASE_DATABASE_NAME
            value: zerobus_sdp
          - name: LAKEBASE_CATALOG_NAME
            value: zerobus_sdp
          - name: LAKEBASE_SCHEMA_NAME
            value: zerobus_sdp
          - name: LAKEBASE_HOST
            value: ${var.database_host_name}
          - name: LAKEBASE_PORT
            value: "5432"
          - name: ENVIRONMENT
            value: production      
      resources:
        - name: sql-warehouse
          sql_warehouse:
            id: ${var.warehouse_id}
            permission: CAN_USE
        # - name: lakebase-instance
        #   database_instance:
        #     instance_name: ${var.database_instance_name}
        #     permission: CAN_USE
        - name: database
          description: "Databricks serving endpoint name for app"
          database:
            database_name: ${var.schema_name}
            instance_name: ${var.database_instance_name}
            permission: CAN_CONNECT_AND_CREATE

