import os

OBSERVABILITY_CATALOG = os.getenv("OBSERVABILITY_CATALOG", "jmr_demo")
OBSERVABILITY_SCHEMA = os.getenv("OBSERVABILITY_SCHEMA", "zerobus")
OBSERVABILITY_TABLE_PREFIX = f"{OBSERVABILITY_CATALOG}.{OBSERVABILITY_SCHEMA}"
