import os

OBSERVABILITY_CATALOG = os.getenv("CATALOG_NAME", "jmr_demo")
OBSERVABILITY_SCHEMA = os.getenv("SCHEMA_NAME", "zerobus")
OBSERVABILITY_TABLE_PREFIX = f"{OBSERVABILITY_CATALOG}.{OBSERVABILITY_SCHEMA}"
